name:                joy
version:             0.1.0.0
github:              "owainlewis/joy"
license:             MIT
author:              "Owain Lewis"
maintainer:          "owain@owainlewis.com"
copyright:           "2020 Owain Lewis"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A compiler / interpreter for the Joy programing language
category:            Language
description:         Please see the README on GitHub at <https://github.com/githubuser/joy#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- text
- mtl
- containers
- parsec >= 3.1.14.0

library:
  source-dirs: src

executables:
  joy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - joy

tests:
  joy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - joy
